package com.kamabizbazti.model.entities;

public enum  ChartSelectionId {
    CURRENT_MONTH_AVG, PREV_MONTH_AVG, PREV_THREE_MONTH_AVG, CUSTOM_PERIOD_AVG,
    LAST_THREE_MONTH_AVG_DETAILED, LAST_SIX_MONTH_AVG_DETAILED, LAST_YEAR_AVG_DETAILED, CUSTOM_PERIOD_AVG_DETAILED
}
