CREATE USER 'budgeez'@'%' IDENTIFIED BY 'password';
GRANT SUPER ON *.* TO 'budgeez'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS budgeez DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON `budgeez`.* TO 'budgeez'@'%';
GRANT ALL PRIVILEGES ON `budgeez\_%`.* TO 'budgeez'@'%';