package com.budgeez.model.enumerations;

public enum ChartSelectionIdEnum {
    CURRENT_MONTH_AVG, PREV_MONTH_AVG, PREV_THREE_MONTHS_AVG, LAST_YEAR_AVG,
    LAST_THREE_MONTHS_AVG_DETAILED, LAST_SIX_MONTHS_AVG_DETAILED, LAST_YEAR_AVG_DETAILED,
    USER_CURRENT_MONTH, USER_PREV_MONTH, USER_PREV_THREE_MONTHS_AVG, USER_PREV_THREE_MONTHS_TOTAL, USER_CUSTOM_PERIOD_AVG, USER_CUSTOM_PERIOD_TOTAL,
    USER_LAST_THREE_MONTHS_DETAILED, USER_LAST_SIX_MONTHS_DETAILED, USER_LAST_YEAR_DETAILED, USER_CUSTOM_PERIOD_DETAILED
}
